#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

for file in .bashrc .bash_profile .bashprompttag .gitconfig .tmux.conf; do
  if [[ ! -s "$HOME/$file" ]]; then
     ln -s "$PWD/$file" "$HOME/$file"
  fi
done

mkdir -p "$HOME/bin/completions"
